version: '3'
services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
